create type "public"."stock_management_type" as enum ('lot_date', 'lot_only', 'serial', 'simple');


  create table "public"."finance_invoice_allocations" (
    "id" bigint generated by default as identity not null,
    "invoice_id" bigint,
    "po_id" bigint,
    "allocated_amount" numeric default 0,
    "note" text,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."finance_invoice_allocations" enable row level security;


  create table "public"."finance_invoices" (
    "id" bigint generated by default as identity not null,
    "invoice_number" text,
    "invoice_symbol" text,
    "invoice_date" date,
    "supplier_name_raw" text,
    "supplier_tax_code" text,
    "supplier_id" bigint,
    "total_amount_pre_tax" numeric default 0,
    "tax_amount" numeric default 0,
    "total_amount_post_tax" numeric default 0,
    "items_json" jsonb default '[]'::jsonb,
    "parsed_data" jsonb,
    "file_url" text not null,
    "file_type" text,
    "status" text default 'draft'::text,
    "created_by" uuid default auth.uid(),
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now(),
    "supplier_address_raw" text
      );


alter table "public"."finance_invoices" enable row level security;

alter table "public"."inventory_receipt_items" add column "qc_status" text default 'pass'::text;

alter table "public"."inventory_receipt_items" add column "serial_number" text;

alter table "public"."products" add column "stock_management_type" public.stock_management_type default 'lot_date'::public.stock_management_type;

CREATE UNIQUE INDEX finance_invoice_allocations_pkey ON public.finance_invoice_allocations USING btree (id);

CREATE UNIQUE INDEX finance_invoices_pkey ON public.finance_invoices USING btree (id);

CREATE INDEX idx_allocations_invoice ON public.finance_invoice_allocations USING btree (invoice_id);

CREATE INDEX idx_allocations_po ON public.finance_invoice_allocations USING btree (po_id);

CREATE INDEX idx_invoices_number ON public.finance_invoices USING btree (invoice_number);

CREATE INDEX idx_invoices_status ON public.finance_invoices USING btree (status);

CREATE INDEX idx_invoices_supplier ON public.finance_invoices USING btree (supplier_id);

alter table "public"."finance_invoice_allocations" add constraint "finance_invoice_allocations_pkey" PRIMARY KEY using index "finance_invoice_allocations_pkey";

alter table "public"."finance_invoices" add constraint "finance_invoices_pkey" PRIMARY KEY using index "finance_invoices_pkey";

alter table "public"."finance_invoice_allocations" add constraint "finance_invoice_allocations_allocated_amount_check" CHECK ((allocated_amount >= (0)::numeric)) not valid;

alter table "public"."finance_invoice_allocations" validate constraint "finance_invoice_allocations_allocated_amount_check";

alter table "public"."finance_invoice_allocations" add constraint "finance_invoice_allocations_invoice_id_fkey" FOREIGN KEY (invoice_id) REFERENCES public.finance_invoices(id) ON DELETE CASCADE not valid;

alter table "public"."finance_invoice_allocations" validate constraint "finance_invoice_allocations_invoice_id_fkey";

alter table "public"."finance_invoice_allocations" add constraint "finance_invoice_allocations_po_id_fkey" FOREIGN KEY (po_id) REFERENCES public.purchase_orders(id) ON DELETE CASCADE not valid;

alter table "public"."finance_invoice_allocations" validate constraint "finance_invoice_allocations_po_id_fkey";

alter table "public"."finance_invoices" add constraint "finance_invoices_status_check" CHECK ((status = ANY (ARRAY['draft'::text, 'verified'::text, 'posted'::text, 'rejected'::text]))) not valid;

alter table "public"."finance_invoices" validate constraint "finance_invoices_status_check";

alter table "public"."finance_invoices" add constraint "finance_invoices_supplier_id_fkey" FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id) ON DELETE SET NULL not valid;

alter table "public"."finance_invoices" validate constraint "finance_invoices_supplier_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.bulk_update_product_strategy(p_product_ids bigint[], p_strategy_type text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
    UPDATE public.products 
    SET stock_management_type = p_strategy_type::public.stock_management_type, 
        updated_at = now()
    WHERE id = ANY(p_product_ids);
END;
$function$
;

CREATE OR REPLACE FUNCTION public.create_inventory_receipt(p_po_id bigint, p_warehouse_id bigint, p_note text, p_items jsonb)
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
    DECLARE
        v_receipt_id BIGINT;
        v_item JSONB;
        v_code TEXT;
    BEGIN
        -- A. Tạo Mã Phiếu Nhập (PNK-YYMMDD-XXXX)
        v_code := 'PNK-' || to_char(now(), 'YYMMDD') || '-' || floor(random() * 10000)::text;

        -- B. Insert Header Phiếu Nhập
        INSERT INTO public.inventory_receipts (
            code, po_id, warehouse_id, creator_id, receipt_date, note, status
        )
        VALUES (
            v_code, p_po_id, p_warehouse_id, auth.uid(), now(), p_note, 'completed'
        )
        RETURNING id INTO v_receipt_id;

        -- C. Insert Chi Tiết & Cập nhật Tồn Kho
        FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
        LOOP
            -- 1. Lưu dòng chi tiết nhập
            INSERT INTO public.inventory_receipt_items (
                receipt_id, product_id, quantity, lot_number, expiry_date
            )
            VALUES (
                v_receipt_id,
                (v_item->>'product_id')::BIGINT,
                (v_item->>'quantity')::INTEGER,
                v_item->>'lot_number',
                (v_item->>'expiry_date')::DATE
            );

            -- 2. Cộng Tồn Kho (Vào bảng product_inventory)
            UPDATE public.product_inventory
            SET stock_quantity = stock_quantity + (v_item->>'quantity')::INTEGER
            WHERE product_id = (v_item->>'product_id')::BIGINT 
              AND warehouse_id = p_warehouse_id;
            
            -- Nếu chưa có dòng tồn kho thì insert (phòng hờ)
            IF NOT FOUND THEN
                INSERT INTO public.product_inventory (product_id, warehouse_id, stock_quantity, min_stock, max_stock)
                VALUES ((v_item->>'product_id')::BIGINT, p_warehouse_id, (v_item->>'quantity')::INTEGER, 0, 100);
            END IF;

            -- 3. Cập nhật số lượng đã nhập vào PO Items (Quan trọng để tính công nợ/đối chiếu)
            UPDATE public.purchase_order_items
            SET quantity_received = COALESCE(quantity_received, 0) + (v_item->>'quantity')::INTEGER
            WHERE po_id = p_po_id 
              AND product_id = (v_item->>'product_id')::BIGINT;
        END LOOP;

        -- D. Cập nhật trạng thái PO thành ĐÃ NHẬP (Theo yêu cầu AURA)
        UPDATE public.purchase_orders
        SET 
            delivery_status = 'delivered', -- Đã giao hàng
            status = 'COMPLETED',          -- Quy trình hoàn tất
            updated_at = now()
        WHERE id = p_po_id;

        RETURN v_receipt_id;
    END;
    $function$
;

grant delete on table "public"."finance_invoice_allocations" to "anon";

grant insert on table "public"."finance_invoice_allocations" to "anon";

grant references on table "public"."finance_invoice_allocations" to "anon";

grant select on table "public"."finance_invoice_allocations" to "anon";

grant trigger on table "public"."finance_invoice_allocations" to "anon";

grant truncate on table "public"."finance_invoice_allocations" to "anon";

grant update on table "public"."finance_invoice_allocations" to "anon";

grant delete on table "public"."finance_invoice_allocations" to "authenticated";

grant insert on table "public"."finance_invoice_allocations" to "authenticated";

grant references on table "public"."finance_invoice_allocations" to "authenticated";

grant select on table "public"."finance_invoice_allocations" to "authenticated";

grant trigger on table "public"."finance_invoice_allocations" to "authenticated";

grant truncate on table "public"."finance_invoice_allocations" to "authenticated";

grant update on table "public"."finance_invoice_allocations" to "authenticated";

grant delete on table "public"."finance_invoice_allocations" to "service_role";

grant insert on table "public"."finance_invoice_allocations" to "service_role";

grant references on table "public"."finance_invoice_allocations" to "service_role";

grant select on table "public"."finance_invoice_allocations" to "service_role";

grant trigger on table "public"."finance_invoice_allocations" to "service_role";

grant truncate on table "public"."finance_invoice_allocations" to "service_role";

grant update on table "public"."finance_invoice_allocations" to "service_role";

grant delete on table "public"."finance_invoices" to "anon";

grant insert on table "public"."finance_invoices" to "anon";

grant references on table "public"."finance_invoices" to "anon";

grant select on table "public"."finance_invoices" to "anon";

grant trigger on table "public"."finance_invoices" to "anon";

grant truncate on table "public"."finance_invoices" to "anon";

grant update on table "public"."finance_invoices" to "anon";

grant delete on table "public"."finance_invoices" to "authenticated";

grant insert on table "public"."finance_invoices" to "authenticated";

grant references on table "public"."finance_invoices" to "authenticated";

grant select on table "public"."finance_invoices" to "authenticated";

grant trigger on table "public"."finance_invoices" to "authenticated";

grant truncate on table "public"."finance_invoices" to "authenticated";

grant update on table "public"."finance_invoices" to "authenticated";

grant delete on table "public"."finance_invoices" to "service_role";

grant insert on table "public"."finance_invoices" to "service_role";

grant references on table "public"."finance_invoices" to "service_role";

grant select on table "public"."finance_invoices" to "service_role";

grant trigger on table "public"."finance_invoices" to "service_role";

grant truncate on table "public"."finance_invoices" to "service_role";

grant update on table "public"."finance_invoices" to "service_role";


  create policy "Enable all for authenticated"
  on "public"."finance_invoice_allocations"
  as permissive
  for all
  to authenticated
using (true);



  create policy "Staff full access allocations"
  on "public"."finance_invoice_allocations"
  as permissive
  for all
  to authenticated
using (true)
with check (true);



  create policy "Staff full access invoices"
  on "public"."finance_invoices"
  as permissive
  for all
  to authenticated
using (true)
with check (true);


CREATE TRIGGER on_invoice_updated BEFORE UPDATE ON public.finance_invoices FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();


  create policy "Allow authenticated users to delete invoices"
  on "storage"."objects"
  as permissive
  for delete
  to authenticated
using ((bucket_id = 'invoices'::text));



  create policy "Allow authenticated users to insert invoices"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check ((bucket_id = 'invoices'::text));



  create policy "Allow authenticated users to select invoices"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using ((bucket_id = 'invoices'::text));



