create type "public"."service_package_type" as enum ('service', 'bundle');

create sequence "public"."service_package_items_id_seq";

create sequence "public"."service_packages_id_seq";

drop function if exists "public"."create_product"(p_name text, p_sku text, p_barcode text, p_active_ingredient text, p_image_url text, p_category_name text, p_manufacturer_name text, p_distributor_id bigint, p_status text, p_invoice_price numeric, p_actual_cost numeric, p_wholesale_unit text, p_retail_unit text, p_conversion_factor integer, p_wholesale_margin_value numeric, p_wholesale_margin_type text, p_retail_margin_value numeric, p_retail_margin_type text, p_inventory_settings jsonb);

drop function if exists "public"."create_supplier"(p_name text, p_contact_person text, p_phone text, p_status text, p_address text, p_notes text);

drop function if exists "public"."create_supplier"(p_name text, p_tax_code text, p_contact_person text, p_phone text, p_email text, p_address text, p_payment_term text, p_status text, p_notes text);

drop function if exists "public"."update_product"(p_id bigint, p_name text, p_sku text, p_barcode text, p_active_ingredient text, p_image_url text, p_category_name text, p_manufacturer_name text, p_distributor_id bigint, p_status text, p_invoice_price numeric, p_actual_cost numeric, p_wholesale_unit text, p_retail_unit text, p_conversion_factor integer, p_wholesale_margin_value numeric, p_wholesale_margin_type text, p_retail_margin_value numeric, p_retail_margin_type text, p_inventory_settings jsonb);

drop function if exists "public"."update_supplier"(p_id bigint, p_name text, p_tax_code text, p_address text, p_contact_person text, p_phone text, p_email text, p_bank_account text, p_bank_name text, p_bank_holder text, p_payment_term text, p_delivery_method text, p_lead_time integer, p_status text, p_notes text);


  create table "public"."inventory_receipt_items" (
    "id" bigint generated by default as identity not null,
    "receipt_id" bigint not null,
    "product_id" bigint not null,
    "quantity" integer not null,
    "lot_number" text,
    "expiry_date" date,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."inventory_receipt_items" enable row level security;


  create table "public"."inventory_receipts" (
    "id" bigint generated by default as identity not null,
    "code" text not null,
    "po_id" bigint,
    "warehouse_id" bigint not null,
    "creator_id" uuid default auth.uid(),
    "receipt_date" timestamp with time zone default now(),
    "note" text,
    "status" text default 'completed'::text,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."inventory_receipts" enable row level security;


  create table "public"."notifications" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid not null,
    "title" text not null,
    "message" text,
    "type" text default 'info'::text,
    "is_read" boolean default false,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."notifications" enable row level security;


  create table "public"."orders" (
    "id" uuid not null default gen_random_uuid(),
    "code" text not null,
    "customer_id" bigint,
    "creator_id" uuid,
    "status" text default 'PENDING'::text,
    "total_amount" numeric default 0,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
      );


alter table "public"."orders" enable row level security;


  create table "public"."prescription_template_items" (
    "id" bigint generated by default as identity not null,
    "template_id" bigint not null,
    "product_id" bigint not null,
    "quantity" integer not null,
    "usage_instruction" text not null
      );


alter table "public"."prescription_template_items" enable row level security;


  create table "public"."prescription_templates" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "diagnosis" text,
    "note" text,
    "status" text default 'active'::text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."prescription_templates" enable row level security;


  create table "public"."promotion_usages" (
    "id" uuid not null default gen_random_uuid(),
    "promotion_id" uuid not null,
    "customer_id" bigint not null,
    "order_id" uuid,
    "created_at" timestamp with time zone default now()
      );



  create table "public"."promotions" (
    "id" uuid not null default gen_random_uuid(),
    "code" text not null,
    "name" text not null,
    "description" text,
    "type" text not null,
    "discount_type" text not null,
    "discount_value" numeric not null default 0,
    "max_discount_value" numeric,
    "min_order_value" numeric default 0,
    "apply_to_scope" text default 'all'::text,
    "apply_to_ids" jsonb,
    "total_usage_limit" integer,
    "usage_count" integer default 0,
    "usage_limit_per_user" integer default 1,
    "customer_id" bigint,
    "valid_from" timestamp with time zone not null default now(),
    "valid_to" timestamp with time zone not null,
    "status" text default 'active'::text,
    "created_at" timestamp with time zone default now()
      );



  create table "public"."purchase_order_items" (
    "id" bigint generated by default as identity not null,
    "po_id" bigint not null,
    "product_id" bigint not null,
    "quantity_ordered" integer not null,
    "quantity_received" integer default 0,
    "unit_price" numeric not null,
    "unit" text,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."purchase_order_items" enable row level security;


  create table "public"."purchase_orders" (
    "id" bigint generated by default as identity not null,
    "code" text not null,
    "supplier_id" bigint not null,
    "creator_id" uuid default auth.uid(),
    "delivery_status" text default 'pending'::text,
    "payment_status" text default 'unpaid'::text,
    "total_amount" numeric not null default 0,
    "discount_amount" numeric default 0,
    "final_amount" numeric not null default 0,
    "total_paid" numeric default 0,
    "expected_delivery_date" timestamp with time zone,
    "note" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "delivery_method" text
      );


alter table "public"."purchase_orders" enable row level security;


  create table "public"."service_package_items" (
    "id" bigint not null default nextval('public.service_package_items_id_seq'::regclass),
    "package_id" bigint not null,
    "item_id" bigint not null,
    "quantity" numeric not null default 1,
    "item_type" text not null default 'consumable'::text,
    "schedule_days" integer default 0
      );


alter table "public"."service_package_items" enable row level security;


  create table "public"."service_packages" (
    "id" bigint not null default nextval('public.service_packages_id_seq'::regclass),
    "name" text not null,
    "sku" text not null,
    "unit" text not null default 'Lần'::text,
    "type" public.service_package_type not null default 'service'::public.service_package_type,
    "price" numeric not null default 0,
    "total_cost_price" numeric not null default 0,
    "revenue_account_id" text,
    "valid_from" date not null,
    "valid_to" date not null,
    "status" public.account_status not null default 'active'::public.account_status,
    "validity_days" integer,
    "applicable_branches" bigint[],
    "applicable_channels" text not null default 'all'::text,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
      );


alter table "public"."service_packages" enable row level security;


  create table "public"."vaccination_template_items" (
    "id" bigint generated by default as identity not null,
    "template_id" bigint not null,
    "product_id" bigint not null,
    "shot_name" text not null,
    "days_after_start" integer default 0,
    "note" text
      );


alter table "public"."vaccination_template_items" enable row level security;


  create table "public"."vaccination_templates" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "description" text,
    "min_age_months" integer,
    "max_age_months" integer,
    "status" text default 'active'::text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."vaccination_templates" enable row level security;

alter table "public"."products" add column "items_per_carton" integer default 1;

alter sequence "public"."service_package_items_id_seq" owned by "public"."service_package_items"."id";

alter sequence "public"."service_packages_id_seq" owned by "public"."service_packages"."id";

CREATE INDEX idx_po_creator_id ON public.purchase_orders USING btree (creator_id);

CREATE INDEX idx_po_items_po_id ON public.purchase_order_items USING btree (po_id);

CREATE INDEX idx_po_items_product_id ON public.purchase_order_items USING btree (product_id);

CREATE INDEX idx_po_status ON public.purchase_orders USING btree (delivery_status, payment_status);

CREATE INDEX idx_po_supplier ON public.purchase_orders USING btree (supplier_id);

CREATE INDEX idx_products_category ON public.products USING btree (category_name);

CREATE INDEX idx_products_distributor ON public.products USING btree (distributor_id);

CREATE INDEX idx_products_items_per_carton ON public.products USING btree (items_per_carton);

CREATE INDEX idx_products_manufacturer ON public.products USING btree (manufacturer_name);

CREATE INDEX idx_receipt_items_product_id ON public.inventory_receipt_items USING btree (product_id);

CREATE INDEX idx_receipt_items_receipt_id ON public.inventory_receipt_items USING btree (receipt_id);

CREATE INDEX idx_receipt_po ON public.inventory_receipts USING btree (po_id);

CREATE INDEX idx_receipts_warehouse_id ON public.inventory_receipts USING btree (warehouse_id);

CREATE INDEX idx_service_package_items_item_id ON public.service_package_items USING btree (item_id);

CREATE INDEX idx_service_package_items_package_id ON public.service_package_items USING btree (package_id);

CREATE INDEX idx_service_packages_name_trgm ON public.service_packages USING gin (name public.gin_trgm_ops);

CREATE INDEX idx_service_packages_sku ON public.service_packages USING btree (sku);

CREATE INDEX idx_template_items_template_id ON public.prescription_template_items USING btree (template_id);

CREATE INDEX idx_templates_diagnosis ON public.prescription_templates USING btree (diagnosis);

CREATE INDEX idx_templates_name ON public.prescription_templates USING btree (name);

CREATE INDEX idx_vacc_items_template_id ON public.vaccination_template_items USING btree (template_id);

CREATE INDEX idx_vacc_templates_name ON public.vaccination_templates USING btree (name);

CREATE UNIQUE INDEX inventory_receipt_items_pkey ON public.inventory_receipt_items USING btree (id);

CREATE UNIQUE INDEX inventory_receipts_code_key ON public.inventory_receipts USING btree (code);

CREATE UNIQUE INDEX inventory_receipts_pkey ON public.inventory_receipts USING btree (id);

CREATE UNIQUE INDEX notifications_pkey ON public.notifications USING btree (id);

CREATE UNIQUE INDEX orders_code_unique ON public.orders USING btree (code);

CREATE UNIQUE INDEX orders_pkey ON public.orders USING btree (id);

CREATE UNIQUE INDEX prescription_template_items_pkey ON public.prescription_template_items USING btree (id);

CREATE UNIQUE INDEX prescription_templates_pkey ON public.prescription_templates USING btree (id);

CREATE UNIQUE INDEX promotion_usages_pkey ON public.promotion_usages USING btree (id);

CREATE UNIQUE INDEX promotion_usages_promotion_id_customer_id_order_id_key ON public.promotion_usages USING btree (promotion_id, customer_id, order_id);

CREATE UNIQUE INDEX promotions_code_key ON public.promotions USING btree (code);

CREATE UNIQUE INDEX promotions_pkey ON public.promotions USING btree (id);

CREATE UNIQUE INDEX purchase_order_items_pkey ON public.purchase_order_items USING btree (id);

CREATE UNIQUE INDEX purchase_orders_code_key ON public.purchase_orders USING btree (code);

CREATE UNIQUE INDEX purchase_orders_pkey ON public.purchase_orders USING btree (id);

CREATE UNIQUE INDEX service_package_items_pkey ON public.service_package_items USING btree (id);

CREATE UNIQUE INDEX service_packages_pkey ON public.service_packages USING btree (id);

CREATE UNIQUE INDEX service_packages_sku_key ON public.service_packages USING btree (sku);

CREATE UNIQUE INDEX vaccination_template_items_pkey ON public.vaccination_template_items USING btree (id);

CREATE UNIQUE INDEX vaccination_templates_pkey ON public.vaccination_templates USING btree (id);

alter table "public"."inventory_receipt_items" add constraint "inventory_receipt_items_pkey" PRIMARY KEY using index "inventory_receipt_items_pkey";

alter table "public"."inventory_receipts" add constraint "inventory_receipts_pkey" PRIMARY KEY using index "inventory_receipts_pkey";

alter table "public"."notifications" add constraint "notifications_pkey" PRIMARY KEY using index "notifications_pkey";

alter table "public"."orders" add constraint "orders_pkey" PRIMARY KEY using index "orders_pkey";

alter table "public"."prescription_template_items" add constraint "prescription_template_items_pkey" PRIMARY KEY using index "prescription_template_items_pkey";

alter table "public"."prescription_templates" add constraint "prescription_templates_pkey" PRIMARY KEY using index "prescription_templates_pkey";

alter table "public"."promotion_usages" add constraint "promotion_usages_pkey" PRIMARY KEY using index "promotion_usages_pkey";

alter table "public"."promotions" add constraint "promotions_pkey" PRIMARY KEY using index "promotions_pkey";

alter table "public"."purchase_order_items" add constraint "purchase_order_items_pkey" PRIMARY KEY using index "purchase_order_items_pkey";

alter table "public"."purchase_orders" add constraint "purchase_orders_pkey" PRIMARY KEY using index "purchase_orders_pkey";

alter table "public"."service_package_items" add constraint "service_package_items_pkey" PRIMARY KEY using index "service_package_items_pkey";

alter table "public"."service_packages" add constraint "service_packages_pkey" PRIMARY KEY using index "service_packages_pkey";

alter table "public"."vaccination_template_items" add constraint "vaccination_template_items_pkey" PRIMARY KEY using index "vaccination_template_items_pkey";

alter table "public"."vaccination_templates" add constraint "vaccination_templates_pkey" PRIMARY KEY using index "vaccination_templates_pkey";

alter table "public"."inventory_receipt_items" add constraint "inventory_receipt_items_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) not valid;

alter table "public"."inventory_receipt_items" validate constraint "inventory_receipt_items_product_id_fkey";

alter table "public"."inventory_receipt_items" add constraint "inventory_receipt_items_quantity_check" CHECK ((quantity > 0)) not valid;

alter table "public"."inventory_receipt_items" validate constraint "inventory_receipt_items_quantity_check";

alter table "public"."inventory_receipt_items" add constraint "inventory_receipt_items_receipt_id_fkey" FOREIGN KEY (receipt_id) REFERENCES public.inventory_receipts(id) ON DELETE CASCADE not valid;

alter table "public"."inventory_receipt_items" validate constraint "inventory_receipt_items_receipt_id_fkey";

alter table "public"."inventory_receipts" add constraint "inventory_receipts_code_key" UNIQUE using index "inventory_receipts_code_key";

alter table "public"."inventory_receipts" add constraint "inventory_receipts_po_id_fkey" FOREIGN KEY (po_id) REFERENCES public.purchase_orders(id) not valid;

alter table "public"."inventory_receipts" validate constraint "inventory_receipts_po_id_fkey";

alter table "public"."inventory_receipts" add constraint "inventory_receipts_warehouse_id_fkey" FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id) not valid;

alter table "public"."inventory_receipts" validate constraint "inventory_receipts_warehouse_id_fkey";

alter table "public"."notifications" add constraint "notifications_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."notifications" validate constraint "notifications_user_id_fkey";

alter table "public"."orders" add constraint "orders_code_unique" UNIQUE using index "orders_code_unique";

alter table "public"."orders" add constraint "orders_creator_id_fkey" FOREIGN KEY (creator_id) REFERENCES auth.users(id) not valid;

alter table "public"."orders" validate constraint "orders_creator_id_fkey";

alter table "public"."prescription_template_items" add constraint "prescription_template_items_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) not valid;

alter table "public"."prescription_template_items" validate constraint "prescription_template_items_product_id_fkey";

alter table "public"."prescription_template_items" add constraint "prescription_template_items_quantity_check" CHECK ((quantity > 0)) not valid;

alter table "public"."prescription_template_items" validate constraint "prescription_template_items_quantity_check";

alter table "public"."prescription_template_items" add constraint "prescription_template_items_template_id_fkey" FOREIGN KEY (template_id) REFERENCES public.prescription_templates(id) ON DELETE CASCADE not valid;

alter table "public"."prescription_template_items" validate constraint "prescription_template_items_template_id_fkey";

alter table "public"."prescription_templates" add constraint "prescription_templates_status_check" CHECK ((status = ANY (ARRAY['active'::text, 'inactive'::text]))) not valid;

alter table "public"."prescription_templates" validate constraint "prescription_templates_status_check";

alter table "public"."products" add constraint "products_items_per_carton_check" CHECK ((items_per_carton > 0)) not valid;

alter table "public"."products" validate constraint "products_items_per_carton_check";

alter table "public"."promotion_usages" add constraint "promotion_usages_customer_id_fkey" FOREIGN KEY (customer_id) REFERENCES public.customers(id) not valid;

alter table "public"."promotion_usages" validate constraint "promotion_usages_customer_id_fkey";

alter table "public"."promotion_usages" add constraint "promotion_usages_promotion_id_customer_id_order_id_key" UNIQUE using index "promotion_usages_promotion_id_customer_id_order_id_key";

alter table "public"."promotion_usages" add constraint "promotion_usages_promotion_id_fkey" FOREIGN KEY (promotion_id) REFERENCES public.promotions(id) not valid;

alter table "public"."promotion_usages" validate constraint "promotion_usages_promotion_id_fkey";

alter table "public"."promotions" add constraint "promotions_code_key" UNIQUE using index "promotions_code_key";

alter table "public"."promotions" add constraint "promotions_customer_id_fkey" FOREIGN KEY (customer_id) REFERENCES public.customers(id) not valid;

alter table "public"."promotions" validate constraint "promotions_customer_id_fkey";

alter table "public"."promotions" add constraint "promotions_discount_type_check" CHECK ((discount_type = ANY (ARRAY['percent'::text, 'fixed'::text]))) not valid;

alter table "public"."promotions" validate constraint "promotions_discount_type_check";

alter table "public"."promotions" add constraint "promotions_status_check" CHECK ((status = ANY (ARRAY['active'::text, 'expired'::text, 'used'::text, 'inactive'::text]))) not valid;

alter table "public"."promotions" validate constraint "promotions_status_check";

alter table "public"."promotions" add constraint "promotions_type_check" CHECK ((type = ANY (ARRAY['public'::text, 'personal'::text, 'point_exchange'::text]))) not valid;

alter table "public"."promotions" validate constraint "promotions_type_check";

alter table "public"."purchase_order_items" add constraint "purchase_order_items_po_id_fkey" FOREIGN KEY (po_id) REFERENCES public.purchase_orders(id) ON DELETE CASCADE not valid;

alter table "public"."purchase_order_items" validate constraint "purchase_order_items_po_id_fkey";

alter table "public"."purchase_order_items" add constraint "purchase_order_items_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) not valid;

alter table "public"."purchase_order_items" validate constraint "purchase_order_items_product_id_fkey";

alter table "public"."purchase_order_items" add constraint "purchase_order_items_quantity_ordered_check" CHECK ((quantity_ordered > 0)) not valid;

alter table "public"."purchase_order_items" validate constraint "purchase_order_items_quantity_ordered_check";

alter table "public"."purchase_order_items" add constraint "purchase_order_items_quantity_received_check" CHECK ((quantity_received >= 0)) not valid;

alter table "public"."purchase_order_items" validate constraint "purchase_order_items_quantity_received_check";

alter table "public"."purchase_order_items" add constraint "purchase_order_items_unit_price_check" CHECK ((unit_price >= (0)::numeric)) not valid;

alter table "public"."purchase_order_items" validate constraint "purchase_order_items_unit_price_check";

alter table "public"."purchase_orders" add constraint "purchase_orders_code_key" UNIQUE using index "purchase_orders_code_key";

alter table "public"."purchase_orders" add constraint "purchase_orders_delivery_status_check" CHECK ((delivery_status = ANY (ARRAY['pending'::text, 'partial'::text, 'delivered'::text, 'cancelled'::text]))) not valid;

alter table "public"."purchase_orders" validate constraint "purchase_orders_delivery_status_check";

alter table "public"."purchase_orders" add constraint "purchase_orders_payment_status_check" CHECK ((payment_status = ANY (ARRAY['unpaid'::text, 'partial'::text, 'paid'::text, 'overpaid'::text]))) not valid;

alter table "public"."purchase_orders" validate constraint "purchase_orders_payment_status_check";

alter table "public"."purchase_orders" add constraint "purchase_orders_supplier_id_fkey" FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id) not valid;

alter table "public"."purchase_orders" validate constraint "purchase_orders_supplier_id_fkey";

alter table "public"."service_package_items" add constraint "service_package_items_item_id_fkey" FOREIGN KEY (item_id) REFERENCES public.products(id) not valid;

alter table "public"."service_package_items" validate constraint "service_package_items_item_id_fkey";

alter table "public"."service_package_items" add constraint "service_package_items_package_id_fkey" FOREIGN KEY (package_id) REFERENCES public.service_packages(id) ON DELETE CASCADE not valid;

alter table "public"."service_package_items" validate constraint "service_package_items_package_id_fkey";

alter table "public"."service_packages" add constraint "service_packages_revenue_account_id_fkey" FOREIGN KEY (revenue_account_id) REFERENCES public.chart_of_accounts(account_code) not valid;

alter table "public"."service_packages" validate constraint "service_packages_revenue_account_id_fkey";

alter table "public"."service_packages" add constraint "service_packages_sku_key" UNIQUE using index "service_packages_sku_key";

alter table "public"."vaccination_template_items" add constraint "vaccination_template_items_days_after_start_check" CHECK ((days_after_start >= 0)) not valid;

alter table "public"."vaccination_template_items" validate constraint "vaccination_template_items_days_after_start_check";

alter table "public"."vaccination_template_items" add constraint "vaccination_template_items_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) not valid;

alter table "public"."vaccination_template_items" validate constraint "vaccination_template_items_product_id_fkey";

alter table "public"."vaccination_template_items" add constraint "vaccination_template_items_template_id_fkey" FOREIGN KEY (template_id) REFERENCES public.vaccination_templates(id) ON DELETE CASCADE not valid;

alter table "public"."vaccination_template_items" validate constraint "vaccination_template_items_template_id_fkey";

alter table "public"."vaccination_templates" add constraint "vaccination_templates_check" CHECK ((max_age_months >= min_age_months)) not valid;

alter table "public"."vaccination_templates" validate constraint "vaccination_templates_check";

alter table "public"."vaccination_templates" add constraint "vaccination_templates_min_age_months_check" CHECK ((min_age_months >= 0)) not valid;

alter table "public"."vaccination_templates" validate constraint "vaccination_templates_min_age_months_check";

alter table "public"."vaccination_templates" add constraint "vaccination_templates_status_check" CHECK ((status = ANY (ARRAY['active'::text, 'inactive'::text]))) not valid;

alter table "public"."vaccination_templates" validate constraint "vaccination_templates_status_check";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.auto_create_purchase_orders_min_max()
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_b2b_warehouse_id BIGINT;
    v_po_count INTEGER := 0;
    v_new_po_id BIGINT;
    v_supplier_id BIGINT;
    v_supplier_record RECORD;
BEGIN
    -- 1. Lấy ID của kho B2B
    SELECT id INTO v_b2b_warehouse_id FROM public.warehouses WHERE key = 'b2b';
    
    IF v_b2b_warehouse_id IS NULL THEN
        RAISE EXCEPTION 'Không tìm thấy kho B2B (key=b2b).';
    END IF;

    -- 2. Tạo bảng tạm chứa danh sách cần mua
    -- (Thay vì dùng Cursor, ta tạo bảng tạm luôn)
    CREATE TEMP TABLE temp_products_to_buy AS
    SELECT 
        p.id as product_id,
        p.distributor_id as supplier_id,
        p.actual_cost as unit_price,
        p.wholesale_unit as unit,
        (inv.max_stock - inv.stock_quantity) as quantity_needed
    FROM public.product_inventory inv
    JOIN public.products p ON inv.product_id = p.id
    WHERE inv.warehouse_id = v_b2b_warehouse_id
      AND inv.stock_quantity < inv.min_stock
      AND p.status = 'active'
      AND p.distributor_id IS NOT NULL
      AND (inv.max_stock - inv.stock_quantity) > 0; -- Chỉ mua nếu số lượng > 0

    -- 3. Loop qua từng NCC có trong bảng tạm
    FOR v_supplier_record IN SELECT DISTINCT supplier_id FROM temp_products_to_buy
    LOOP
        v_supplier_id := v_supplier_record.supplier_id;

        -- Tạo Header PO
        INSERT INTO public.purchase_orders (
            code, supplier_id, delivery_status, payment_status, note, created_at, updated_at
        ) VALUES (
            'PO-AUTO-' || to_char(now(), 'YYMMDD') || '-' || v_supplier_id || '-' || floor(random()*1000)::text,
            v_supplier_id,
            'pending', 'unpaid',
            'Đơn dự trù tự động (Min/Max)',
            now(), now()
        ) RETURNING id INTO v_new_po_id;

        -- Tạo Items từ bảng tạm
        INSERT INTO public.purchase_order_items (
            po_id, product_id, quantity_ordered, unit_price, unit
        )
        SELECT 
            v_new_po_id, product_id, quantity_needed, unit_price, unit
        FROM temp_products_to_buy
        WHERE supplier_id = v_supplier_id;

        -- Cập nhật tổng tiền
        UPDATE public.purchase_orders
        SET 
            total_amount = (SELECT COALESCE(SUM(quantity_ordered * unit_price), 0) FROM public.purchase_order_items WHERE po_id = v_new_po_id),
            final_amount = (SELECT COALESCE(SUM(quantity_ordered * unit_price), 0) FROM public.purchase_order_items WHERE po_id = v_new_po_id)
        WHERE id = v_new_po_id;

        v_po_count := v_po_count + 1;
    END LOOP;

    -- Dọn dẹp
    DROP TABLE temp_products_to_buy;

    RETURN v_po_count;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.calculate_package_cost(p_items jsonb)
 RETURNS numeric
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_total_cost NUMERIC := 0;
  v_item JSONB;
  v_product_cost NUMERIC;
BEGIN
  -- 1. Loop qua từng item trong mảng JSON
  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    -- 2. Lấy giá vốn (actual_cost) của sản phẩm/dịch vụ con từ bảng 'products'
    SELECT COALESCE(p.actual_cost, 0)
    INTO v_product_cost
    FROM public.products p
    WHERE p.id = (v_item->>'item_id')::BIGINT;
    
    -- 3. Cộng dồn vào tổng giá vốn
    v_total_cost := v_total_cost + (v_product_cost * (v_item->>'quantity')::NUMERIC);
  END LOOP;
  
  RETURN v_total_cost;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.create_prescription_template(p_data jsonb, p_items jsonb)
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_new_id BIGINT;
    v_item JSONB;
BEGIN
    -- Insert Header
    INSERT INTO public.prescription_templates (name, diagnosis, note, status)
    VALUES (
        p_data->>'name',
        p_data->>'diagnosis',
        p_data->>'note',
        COALESCE(p_data->>'status', 'active')
    )
    RETURNING id INTO v_new_id;

    -- Insert Items
    FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
    LOOP
        INSERT INTO public.prescription_template_items (template_id, product_id, quantity, usage_instruction)
        VALUES (
            v_new_id,
            (v_item->>'product_id')::BIGINT, -- <-- QUAN TRỌNG: Ép kiểu sang BIGINT
            (v_item->>'quantity')::INTEGER,
            v_item->>'usage_instruction'
        );
    END LOOP;

    RETURN v_new_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.create_product(p_name text, p_sku text, p_barcode text, p_active_ingredient text, p_image_url text, p_category_name text, p_manufacturer_name text, p_distributor_id bigint, p_status text, p_invoice_price numeric, p_actual_cost numeric, p_wholesale_unit text, p_retail_unit text, p_conversion_factor integer, p_wholesale_margin_value numeric, p_wholesale_margin_type text, p_retail_margin_value numeric, p_retail_margin_type text, p_items_per_carton integer, p_inventory_settings jsonb)
 RETURNS bigint
 LANGUAGE plpgsql
AS $function$
DECLARE
    v_product_id BIGINT;
    v_warehouse_key TEXT;
    v_warehouse_id BIGINT;
    v_min_stock INT;
    v_max_stock INT;
BEGIN
    -- Insert Sản phẩm
    INSERT INTO public.products (
        name, sku, barcode, active_ingredient, image_url,
        category_name, manufacturer_name, distributor_id, status,
        invoice_price, actual_cost, wholesale_unit, retail_unit, conversion_factor,
        wholesale_margin_value, wholesale_margin_type, retail_margin_value, retail_margin_type,
        items_per_carton -- <-- CẬP NHẬT
    )
    VALUES (
        p_name, p_sku, p_barcode, p_active_ingredient, p_image_url,
        p_category_name, p_manufacturer_name, p_distributor_id, p_status,
        p_invoice_price, p_actual_cost, p_wholesale_unit, p_retail_unit, p_conversion_factor,
        p_wholesale_margin_value, p_wholesale_margin_type, p_retail_margin_value, p_retail_margin_type,
        COALESCE(p_items_per_carton, 1) -- Mặc định là 1
    )
    RETURNING id INTO v_product_id;

    -- Insert Tồn kho Min/Max
    FOR v_warehouse_key IN SELECT * FROM jsonb_object_keys(p_inventory_settings)
    LOOP
        SELECT id INTO v_warehouse_id FROM public.warehouses WHERE key = v_warehouse_key;
        IF v_warehouse_id IS NOT NULL THEN
            v_min_stock := (p_inventory_settings -> v_warehouse_key ->> 'min')::INT;
            v_max_stock := (p_inventory_settings -> v_warehouse_key ->> 'max')::INT;

            INSERT INTO public.product_inventory (product_id, warehouse_id, stock_quantity, min_stock, max_stock)
            VALUES (v_product_id, v_warehouse_id, 0, v_min_stock, v_max_stock);
        END IF;
    END LOOP;

    RETURN v_product_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.create_purchase_order(p_data jsonb, p_items jsonb)
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_new_id BIGINT;
    v_code TEXT;
    v_item JSONB;
    v_total_amount NUMERIC := 0;
    v_final_amount NUMERIC := 0;
BEGIN
    -- Tạo mã PO tự động nếu không truyền (PO-YYMMDD-XXXX)
    v_code := COALESCE(p_data->>'code', 'PO-' || to_char(now(), 'YYMMDD') || '-' || floor(random() * 10000)::text);

    -- Tính tổng tiền
    FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
    LOOP
        v_total_amount := v_total_amount + ((v_item->>'quantity_ordered')::INTEGER * (v_item->>'unit_price')::NUMERIC);
    END LOOP;

    v_final_amount := v_total_amount - COALESCE((p_data->>'discount_amount')::NUMERIC, 0);
    IF v_final_amount < 0 THEN v_final_amount := 0; END IF;

    -- Insert Header
    INSERT INTO public.purchase_orders (
        code, supplier_id, expected_delivery_date, 
        total_amount, discount_amount, final_amount, note,
        delivery_status, payment_status
    ) VALUES (
        v_code,
        (p_data->>'supplier_id')::BIGINT,
        (p_data->>'expected_delivery_date')::TIMESTAMPTZ,
        v_total_amount,
        COALESCE((p_data->>'discount_amount')::NUMERIC, 0),
        v_final_amount,
        p_data->>'note',
        'pending', 'unpaid'
    ) RETURNING id INTO v_new_id;

    -- Insert Items
    FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
    LOOP
        INSERT INTO public.purchase_order_items (
            po_id, product_id, quantity_ordered, unit_price, unit
        ) VALUES (
            v_new_id,
            (v_item->>'product_id')::BIGINT,
            (v_item->>'quantity_ordered')::INTEGER,
            (v_item->>'unit_price')::NUMERIC,
            v_item->>'unit'
        );
    END LOOP;

    RETURN v_new_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.create_service_package(p_data jsonb, p_items jsonb)
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_package_id BIGINT;
  v_calculated_cost NUMERIC;
  v_item JSONB;
BEGIN
  -- 1. Gọi "Cỗ máy #1" để tính giá vốn thực tế
  v_calculated_cost := public.calculate_package_cost(p_items);

  -- 2. Thêm vào bảng chính (service_packages)
  INSERT INTO public.service_packages (
    name, sku, unit, type,
    price, total_cost_price, -- Dùng giá vốn đã tính
    revenue_account_id,
    valid_from, valid_to, status,
    validity_days,
    applicable_branches,
    applicable_channels
  )
  VALUES (
    p_data->>'name',
    p_data->>'sku',
    p_data->>'unit',
    (p_data->>'type')::public.service_package_type,
    (p_data->>'price')::NUMERIC,
    v_calculated_cost, -- Dùng giá vốn đã tính
    p_data->>'revenueAccountId',
    (p_data->>'validFrom')::DATE,
    (p_data->>'validTo')::DATE,
    (p_data->>'status')::public.account_status,
    (p_data->>'validityDays')::INT,
    (SELECT array_agg(value::BIGINT) FROM jsonb_array_elements_text(p_data->'applicableBranches') AS t(value)),
    p_data->>'applicableChannels'
  )
  RETURNING id INTO v_package_id;

  -- 3. Loop qua mảng items và thêm vào bảng con (service_package_items)
  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    INSERT INTO public.service_package_items (
      package_id,
      item_id,
      quantity,
      item_type,
      schedule_days
    )
    VALUES (
      v_package_id,
      (v_item->>'item_id')::BIGINT,
      (v_item->>'quantity')::NUMERIC,
      (v_item->>'item_type')::TEXT,
      (v_item->>'schedule_days')::INT
    );
  END LOOP;
  
  RETURN v_package_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.create_supplier(p_name text, p_tax_code text, p_contact_person text, p_phone text, p_email text, p_address text, p_payment_term text, p_bank_account text, p_bank_name text, p_bank_holder text, p_delivery_method text, p_lead_time integer, p_status text, p_notes text)
 RETURNS bigint
 LANGUAGE plpgsql
AS $function$
DECLARE
    v_supplier_id BIGINT;
BEGIN
    INSERT INTO public.suppliers (
        name, tax_code, contact_person, phone, email, address, 
        payment_term, bank_account, bank_name, bank_holder, delivery_method, lead_time,
        status, notes
    )
    VALUES (
        p_name, p_tax_code, p_contact_person, p_phone, p_email, p_address, 
        p_payment_term, p_bank_account, p_bank_name, p_bank_holder, p_delivery_method, p_lead_time,
        p_status, p_notes
    )
    RETURNING id INTO v_supplier_id;
    
    RETURN v_supplier_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.create_vaccination_template(p_data jsonb, p_items jsonb)
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_new_id BIGINT;
    v_item JSONB;
BEGIN
    INSERT INTO public.vaccination_templates (name, description, min_age_months, max_age_months, status)
    VALUES (
        p_data->>'name',
        p_data->>'description',
        (p_data->>'min_age_months')::INTEGER,
        (p_data->>'max_age_months')::INTEGER,
        COALESCE(p_data->>'status', 'active')
    )
    RETURNING id INTO v_new_id;

    FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
    LOOP
        INSERT INTO public.vaccination_template_items (template_id, product_id, shot_name, days_after_start, note)
        VALUES (
            v_new_id,
            (v_item->>'product_id')::BIGINT,
            v_item->>'shot_name',
            COALESCE((v_item->>'days_after_start')::INTEGER, 0),
            v_item->>'note'
        );
    END LOOP;

    RETURN v_new_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.delete_prescription_template(p_id bigint)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
    DELETE FROM public.prescription_template_items WHERE template_id = p_id;
    DELETE FROM public.prescription_templates WHERE id = p_id;
    RETURN TRUE;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.delete_purchase_order(p_id bigint)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_status TEXT;
BEGIN
    SELECT delivery_status INTO v_status FROM public.purchase_orders WHERE id = p_id;
    IF v_status <> 'pending' THEN
        RAISE EXCEPTION 'Không thể xóa Đơn hàng đã có dữ liệu nhập kho.';
    END IF;
    
    DELETE FROM public.purchase_orders WHERE id = p_id;
    RETURN TRUE;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.delete_vaccination_template(p_id bigint)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
    DELETE FROM public.vaccination_templates WHERE id = p_id;
    RETURN TRUE;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_distinct_categories()
 RETURNS TABLE(category_name text)
 LANGUAGE sql
AS $function$
  SELECT DISTINCT category_name 
  FROM public.products 
  WHERE category_name IS NOT NULL AND category_name <> ''
  ORDER BY category_name;
$function$
;

CREATE OR REPLACE FUNCTION public.get_distinct_manufacturers()
 RETURNS TABLE(manufacturer_name text)
 LANGUAGE sql
AS $function$
  SELECT DISTINCT manufacturer_name 
  FROM public.products 
  WHERE manufacturer_name IS NOT NULL AND manufacturer_name <> ''
  ORDER BY manufacturer_name;
$function$
;

CREATE OR REPLACE FUNCTION public.get_prescription_template_details(p_id bigint)
 RETURNS json
 LANGUAGE plpgsql
AS $function$
DECLARE
    v_template RECORD;
    v_items JSON;
BEGIN
    -- Lấy Header
    SELECT * INTO v_template FROM public.prescription_templates WHERE id = p_id;
    
    IF v_template IS NULL THEN RETURN NULL; END IF;

    -- Lấy Items (FIX: product_id là BIGINT nên join bình thường)
    SELECT json_agg(json_build_object(
        'id', i.id,
        'product_id', i.product_id,
        'product_name', p.name,
        'product_unit', p.retail_unit, -- Giả sử bảng products có cột retail_unit
        'quantity', i.quantity,
        'usage_instruction', i.usage_instruction
    ))
    INTO v_items
    FROM public.prescription_template_items i
    JOIN public.products p ON i.product_id = p.id
    WHERE i.template_id = p_id;

    RETURN json_build_object(
        'template', row_to_json(v_template),
        'items', COALESCE(v_items, '[]'::json)
    );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_prescription_templates(p_search text DEFAULT NULL::text, p_status text DEFAULT NULL::text)
 RETURNS SETOF public.prescription_templates
 LANGUAGE plpgsql
AS $function$
BEGIN
    RETURN QUERY
    SELECT *
    FROM public.prescription_templates
    WHERE 
        (p_status IS NULL OR status = p_status)
        AND
        (p_search IS NULL OR name ILIKE '%' || p_search || '%' OR diagnosis ILIKE '%' || p_search || '%')
    ORDER BY created_at DESC;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_purchase_order_details(p_id bigint)
 RETURNS json
 LANGUAGE plpgsql
AS $function$
DECLARE
    v_po RECORD;
    v_items JSON;
BEGIN
    SELECT po.*, s.name as supplier_name 
    INTO v_po 
    FROM public.purchase_orders po
    LEFT JOIN public.suppliers s ON po.supplier_id = s.id
    WHERE po.id = p_id;
    
    IF v_po IS NULL THEN RETURN NULL; END IF;
    
    SELECT json_agg(json_build_object(
        'id', poi.id,
        'product_id', poi.product_id,
        'product_name', prod.name,
        'product_sku', prod.sku,
        'quantity_ordered', poi.quantity_ordered,
        'quantity_received', poi.quantity_received,
        'unit_price', poi.unit_price,
        'unit', poi.unit,
        'total_line', (poi.quantity_ordered * poi.unit_price)
    )) INTO v_items
    FROM public.purchase_order_items poi
    JOIN public.products prod ON poi.product_id = prod.id
    WHERE poi.po_id = p_id;
    
    RETURN json_build_object(
        'po', row_to_json(v_po),
        'items', COALESCE(v_items, '[]'::json)
    );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_purchase_orders_master(p_page integer DEFAULT 1, p_page_size integer DEFAULT 10, p_search text DEFAULT NULL::text, p_status_delivery text DEFAULT NULL::text, p_status_payment text DEFAULT NULL::text, p_date_from timestamp with time zone DEFAULT NULL::timestamp with time zone, p_date_to timestamp with time zone DEFAULT NULL::timestamp with time zone)
 RETURNS TABLE(id bigint, code text, supplier_id bigint, supplier_name text, delivery_method text, delivery_status text, payment_status text, final_amount numeric, total_quantity bigint, total_cartons numeric, total_paid numeric, expected_delivery_date timestamp with time zone, created_at timestamp with time zone, progress_delivery numeric, progress_payment numeric, full_count bigint)
 LANGUAGE plpgsql
AS $function$
BEGIN
    RETURN QUERY
    WITH po_metrics AS (
        SELECT 
            po.id,
            -- Tính % Hàng về
            COALESCE(ROUND((SUM(poi.quantity_received)::NUMERIC / NULLIF(SUM(poi.quantity_ordered), 0)) * 100, 2), 0) AS calc_delivery_progress,
            
            -- Tính Tổng số lượng lẻ
            COALESCE(SUM(poi.quantity_ordered), 0) as total_qty,

            -- TÍNH TỔNG SỐ THÙNG (Logic Logistics V2)
            -- Công thức: SUM( SL Đặt / Quy cách đóng gói )
            -- Nếu items_per_carton là null hoặc 0 thì coi như 1 (An toàn tuyệt đối)
            ROUND(
                SUM(
                    poi.quantity_ordered::NUMERIC / 
                    COALESCE(NULLIF(p.items_per_carton, 0), 1) 
                ), 
                1 -- Làm tròn 1 số thập phân (VD: 10.5 thùng)
            ) AS calc_total_cartons
        FROM public.purchase_orders po
        LEFT JOIN public.purchase_order_items poi ON po.id = poi.po_id
        LEFT JOIN public.products p ON poi.product_id = p.id -- Join để lấy quy cách
        GROUP BY po.id
    )
    SELECT 
        po.id, po.code, po.supplier_id, 
        s.name as supplier_name,
        -- Logic lấy vận chuyển: Ưu tiên đơn hàng, nếu không có thì lấy mặc định của NCC, không có nữa thì 'Unknown'
        COALESCE(po.delivery_method, s.delivery_method, 'Unknown') as delivery_method,
        po.delivery_status, po.payment_status,
        po.final_amount, 
        pm.total_qty as total_quantity,
        pm.calc_total_cartons as total_cartons, -- Trả về số thùng
        po.total_paid, po.expected_delivery_date, po.created_at,
        pm.calc_delivery_progress AS progress_delivery,
        COALESCE(ROUND((po.total_paid / NULLIF(po.final_amount, 0)) * 100, 2), 0) AS progress_payment,
        COUNT(*) OVER() AS full_count
    FROM public.purchase_orders po
    JOIN po_metrics pm ON po.id = pm.id
    LEFT JOIN public.suppliers s ON po.supplier_id = s.id
    WHERE 
        (p_status_delivery IS NULL OR po.delivery_status = p_status_delivery)
        AND (p_status_payment IS NULL OR po.payment_status = p_status_payment)
        AND (p_search IS NULL OR po.code ILIKE '%' || p_search || '%')
        AND (p_date_from IS NULL OR po.created_at >= p_date_from)
        AND (p_date_to IS NULL OR po.created_at <= p_date_to)
    ORDER BY po.created_at DESC
    LIMIT p_page_size OFFSET (p_page - 1) * p_page_size;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_service_package_details(p_id bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_details JSONB;
BEGIN
  SELECT
    jsonb_build_object(
      -- 1. Thông tin chính (từ bảng 'service_packages')
      'package_data', to_jsonb(p.*),
      
      -- 2. Gom mảng items con (từ bảng 'service_package_items')
      'package_items', (
        SELECT COALESCE(jsonb_agg(
          jsonb_build_object(
            'key', i.id,
            'item_id', i.item_id,
            'quantity', i.quantity,
            'item_type', i.item_type,
            'schedule_days', i.schedule_days,
            -- Tích hợp: Lấy tên và đơn vị từ bảng 'products'
            'name', prod.name,
            'unit', prod.retail_unit -- Mặc định lấy đơn vị lẻ
          )
        ), '[]'::JSONB)
        FROM public.service_package_items i
        JOIN public.products prod ON i.item_id = prod.id
        WHERE i.package_id = p.id
      )
    )
  INTO v_details
  FROM public.service_packages p
  WHERE p.id = p_id;
  
  RETURN v_details;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_service_packages_list(p_search_query text, p_type_filter text, p_status_filter text, p_page_num integer, p_page_size integer)
 RETURNS TABLE(key text, id bigint, name text, sku text, type public.service_package_type, price numeric, total_cost_price numeric, valid_from date, valid_to date, status public.account_status, total_count bigint)
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  RETURN QUERY
  WITH filtered_data AS (
    SELECT
      s.id,
      s.name,
      s.sku,
      s.type,
      s.price,
      s.total_cost_price,
      s.valid_from,
      s.valid_to,
      s.status,
      COUNT(*) OVER() AS total_count
    FROM
      public.service_packages s
    WHERE
      (p_type_filter IS NULL OR s.type = p_type_filter::public.service_package_type)
    AND
      (p_status_filter IS NULL OR s.status = p_status_filter::public.account_status)
    AND
      (p_search_query IS NULL OR p_search_query = '' OR
        s.name ILIKE ('%' || p_search_query || '%') OR
        s.sku ILIKE ('%' || p_search_query || '%')
      )
  )
  SELECT
    fd.id::TEXT AS key,
    fd.*
  FROM
    filtered_data fd
  ORDER BY
    fd.id DESC
  LIMIT p_page_size
  OFFSET (p_page_num - 1) * p_page_size;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_vaccination_template_details(p_id bigint)
 RETURNS json
 LANGUAGE plpgsql
AS $function$
DECLARE
    v_template RECORD;
    v_items JSON;
BEGIN
    SELECT * INTO v_template FROM public.vaccination_templates WHERE id = p_id;
    IF v_template IS NULL THEN RETURN NULL; END IF;

    SELECT json_agg(json_build_object(
        'id', i.id,
        'product_id', i.product_id,
        'product_name', p.name,
        'product_sku', p.sku, -- Thêm SKU cho dễ nhìn
        'shot_name', i.shot_name,
        'days_after_start', i.days_after_start,
        'note', i.note
    ) ORDER BY i.days_after_start ASC)
    INTO v_items
    FROM public.vaccination_template_items i
    LEFT JOIN public.products p ON i.product_id = p.id
    WHERE i.template_id = p_id;

    RETURN json_build_object(
        'template', row_to_json(v_template),
        'items', COALESCE(v_items, '[]'::json)
    );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_vaccination_templates(p_search text DEFAULT NULL::text, p_status text DEFAULT NULL::text)
 RETURNS TABLE(id bigint, name text, description text, min_age_months integer, max_age_months integer, status text, created_at timestamp with time zone, updated_at timestamp with time zone, item_count bigint)
 LANGUAGE plpgsql
AS $function$
BEGIN
    RETURN QUERY
    SELECT 
        t.id,
        t.name,
        t.description,
        t.min_age_months,
        t.max_age_months,
        t.status,
        t.created_at,
        t.updated_at,
        (SELECT COUNT(*) FROM public.vaccination_template_items i WHERE i.template_id = t.id) AS item_count -- Logic đếm
    FROM public.vaccination_templates t
    WHERE 
        (p_status IS NULL OR t.status = p_status)
        AND
        (p_search IS NULL OR t.name ILIKE '%' || p_search || '%')
    ORDER BY t.created_at DESC;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_prescription_template(p_id bigint, p_data jsonb, p_items jsonb)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_item JSONB;
BEGIN
    -- Update Header
    UPDATE public.prescription_templates
    SET 
        name = COALESCE(p_data->>'name', name),
        diagnosis = COALESCE(p_data->>'diagnosis', diagnosis),
        note = COALESCE(p_data->>'note', note),
        status = COALESCE(p_data->>'status', status),
        updated_at = NOW()
    WHERE id = p_id;

    -- Replace Items
    DELETE FROM public.prescription_template_items WHERE template_id = p_id;

    FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
    LOOP
        INSERT INTO public.prescription_template_items (template_id, product_id, quantity, usage_instruction)
        VALUES (
            p_id,
            (v_item->>'product_id')::BIGINT, -- <-- QUAN TRỌNG: Ép kiểu sang BIGINT
            (v_item->>'quantity')::INTEGER,
            v_item->>'usage_instruction'
        );
    END LOOP;

    RETURN TRUE;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_product(p_id bigint, p_name text, p_sku text, p_barcode text, p_active_ingredient text, p_image_url text, p_category_name text, p_manufacturer_name text, p_distributor_id bigint, p_status text, p_invoice_price numeric, p_actual_cost numeric, p_wholesale_unit text, p_retail_unit text, p_conversion_factor integer, p_wholesale_margin_value numeric, p_wholesale_margin_type text, p_retail_margin_value numeric, p_retail_margin_type text, p_items_per_carton integer, p_inventory_settings jsonb)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE
    v_warehouse_key TEXT;
    v_warehouse_id BIGINT;
    v_min_stock INT;
    v_max_stock INT;
BEGIN
    -- Update Sản phẩm
    UPDATE public.products
    SET
        name = p_name,
        sku = p_sku,
        barcode = p_barcode,
        active_ingredient = p_active_ingredient,
        image_url = p_image_url,
        category_name = p_category_name,
        manufacturer_name = p_manufacturer_name,
        distributor_id = p_distributor_id,
        status = p_status,
        invoice_price = p_invoice_price,
        actual_cost = p_actual_cost,
        wholesale_unit = p_wholesale_unit,
        retail_unit = p_retail_unit,
        conversion_factor = p_conversion_factor,
        wholesale_margin_value = p_wholesale_margin_value,
        wholesale_margin_type = p_wholesale_margin_type,
        retail_margin_value = p_retail_margin_value,
        retail_margin_type = p_retail_margin_type,
        items_per_carton = COALESCE(p_items_per_carton, 1), -- <-- CẬP NHẬT
        updated_at = now()
    WHERE id = p_id;

    -- Update Tồn kho Min/Max (Xóa cũ thêm mới cho an toàn)
    DELETE FROM public.product_inventory WHERE product_id = p_id;

    FOR v_warehouse_key IN SELECT * FROM jsonb_object_keys(p_inventory_settings)
    LOOP
        SELECT id INTO v_warehouse_id FROM public.warehouses WHERE key = v_warehouse_key;
        IF v_warehouse_id IS NOT NULL THEN
            v_min_stock := (p_inventory_settings -> v_warehouse_key ->> 'min')::INT;
            v_max_stock := (p_inventory_settings -> v_warehouse_key ->> 'max')::INT;

            INSERT INTO public.product_inventory (product_id, warehouse_id, stock_quantity, min_stock, max_stock)
            VALUES (p_id, v_warehouse_id, 0, v_min_stock, v_max_stock)
            ON CONFLICT (product_id, warehouse_id) 
            DO UPDATE SET min_stock = EXCLUDED.min_stock, max_stock = EXCLUDED.max_stock;
        END IF;
    END LOOP;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_purchase_order(p_id bigint, p_data jsonb, p_items jsonb)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_status TEXT;
    v_item JSONB;
    v_total_amount NUMERIC := 0;
    v_final_amount NUMERIC := 0;
BEGIN
    -- QA CHECK: Chỉ được sửa khi chưa nhập hàng (pending)
    SELECT delivery_status INTO v_status FROM public.purchase_orders WHERE id = p_id;
    IF v_status <> 'pending' THEN
        RAISE EXCEPTION 'Không thể sửa Đơn hàng đã bắt đầu nhập kho hoặc đã hoàn tất.';
    END IF;

    -- Tính lại tiền
    FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
    LOOP
        v_total_amount := v_total_amount + ((v_item->>'quantity_ordered')::INTEGER * (v_item->>'unit_price')::NUMERIC);
    END LOOP;
    v_final_amount := v_total_amount - COALESCE((p_data->>'discount_amount')::NUMERIC, 0);

    -- Update Header
    UPDATE public.purchase_orders
    SET 
        supplier_id = COALESCE((p_data->>'supplier_id')::BIGINT, supplier_id),
        expected_delivery_date = (p_data->>'expected_delivery_date')::TIMESTAMPTZ,
        total_amount = v_total_amount,
        discount_amount = COALESCE((p_data->>'discount_amount')::NUMERIC, discount_amount),
        final_amount = v_final_amount,
        note = p_data->>'note',
        updated_at = NOW()
    WHERE id = p_id;

    -- Replace Items
    DELETE FROM public.purchase_order_items WHERE po_id = p_id;
    FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
    LOOP
        INSERT INTO public.purchase_order_items (po_id, product_id, quantity_ordered, unit_price, unit)
        VALUES (p_id, (v_item->>'product_id')::BIGINT, (v_item->>'quantity_ordered')::INTEGER, (v_item->>'unit_price')::NUMERIC, v_item->>'unit');
    END LOOP;

    RETURN TRUE;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_service_package(p_id bigint, p_data jsonb, p_items jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_calculated_cost NUMERIC;
  v_item JSONB;
BEGIN
  -- 1. Tính lại giá vốn mới
  v_calculated_cost := public.calculate_package_cost(p_items);

  -- 2. Cập nhật bảng chính
  UPDATE public.service_packages
  SET
    name = p_data->>'name',
    sku = p_data->>'sku',
    unit = p_data->>'unit',
    type = (p_data->>'type')::public.service_package_type,
    price = (p_data->>'price')::NUMERIC,
    total_cost_price = v_calculated_cost, -- Cập nhật giá vốn mới
    revenue_account_id = p_data->>'revenueAccountId',
    valid_from = (p_data->>'validFrom')::DATE,
    valid_to = (p_data->>'validTo')::DATE,
    status = (p_data->>'status')::public.account_status,
    validity_days = (p_data->>'validityDays')::INT,
    applicable_branches = (SELECT array_agg(value::BIGINT) FROM jsonb_array_elements_text(p_data->'applicableBranches') AS t(value)),
    applicable_channels = p_data->>'applicableChannels',
    updated_at = now()
  WHERE id = p_id;

  -- 3. Xóa sạch các items con cũ
  DELETE FROM public.service_package_items WHERE package_id = p_id;
  
  -- 4. Thêm lại các items con mới
  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    INSERT INTO public.service_package_items (
      package_id, item_id, quantity, item_type, schedule_days
    )
    VALUES (
      p_id,
      (v_item->>'item_id')::BIGINT,
      (v_item->>'quantity')::NUMERIC,
      (v_item->>'item_type')::TEXT,
      (v_item->>'schedule_days')::INT
    );
  END LOOP;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_supplier(p_id bigint, p_name text, p_tax_code text, p_contact_person text, p_phone text, p_email text, p_address text, p_payment_term text, p_bank_account text, p_bank_name text, p_bank_holder text, p_delivery_method text, p_lead_time integer, p_status text, p_notes text)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
    UPDATE public.suppliers
    SET
        name = p_name,
        tax_code = p_tax_code,
        contact_person = p_contact_person,
        phone = p_phone,
        email = p_email,
        address = p_address,
        payment_term = p_payment_term,
        bank_account = p_bank_account,
        bank_name = p_bank_name,
        bank_holder = p_bank_holder,
        delivery_method = p_delivery_method,
        lead_time = p_lead_time,
        status = p_status,
        notes = p_notes
    WHERE id = p_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_vaccination_template(p_id bigint, p_data jsonb, p_items jsonb)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_item JSONB;
BEGIN
    UPDATE public.vaccination_templates
    SET 
        name = COALESCE(p_data->>'name', name),
        description = COALESCE(p_data->>'description', description),
        min_age_months = (p_data->>'min_age_months')::INTEGER,
        max_age_months = (p_data->>'max_age_months')::INTEGER,
        status = COALESCE(p_data->>'status', status),
        updated_at = NOW()
    WHERE id = p_id;

    DELETE FROM public.vaccination_template_items WHERE template_id = p_id;

    FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
    LOOP
        INSERT INTO public.vaccination_template_items (template_id, product_id, shot_name, days_after_start, note)
        VALUES (
            p_id,
            (v_item->>'product_id')::BIGINT,
            v_item->>'shot_name',
            COALESCE((v_item->>'days_after_start')::INTEGER, 0),
            v_item->>'note'
        );
    END LOOP;

    RETURN TRUE;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.verify_promotion_code(p_code text, p_customer_id bigint, p_order_value numeric)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
    v_promo record;
    v_user_usage_count integer;
    v_discount_amount numeric := 0;
begin
    -- Lấy thông tin mã
    select * into v_promo from public.promotions where code = p_code;

    -- Các bước kiểm tra cơ bản
    if v_promo is null then return json_build_object('valid', false, 'message', 'Mã không tồn tại.'); end if;
    if v_promo.status <> 'active' then return json_build_object('valid', false, 'message', 'Mã ngưng hoạt động.'); end if;
    if now() < v_promo.valid_from or now() > v_promo.valid_to then return json_build_object('valid', false, 'message', 'Mã hết hạn.'); end if;
    if v_promo.total_usage_limit is not null and v_promo.usage_count >= v_promo.total_usage_limit then return json_build_object('valid', false, 'message', 'Mã đã hết lượt toàn sàn.'); end if;
    if p_order_value < v_promo.min_order_value then return json_build_object('valid', false, 'message', 'Chưa đạt giá trị đơn hàng tối thiểu.'); end if;

    -- Kiểm tra sở hữu (Nếu là mã riêng)
    if v_promo.type in ('personal', 'point_exchange') and v_promo.customer_id is not null and v_promo.customer_id <> p_customer_id then
        return json_build_object('valid', false, 'message', 'Mã này không áp dụng cho tài khoản của bạn.');
    end if;

    -- Kiểm tra giới hạn số lần dùng của người này
    select count(*) into v_user_usage_count
    from public.promotion_usages
    where promotion_id = v_promo.id and customer_id = p_customer_id;

    if v_promo.usage_limit_per_user is not null and v_user_usage_count >= v_promo.usage_limit_per_user then
        return json_build_object('valid', false, 'message', 'Bạn đã dùng hết số lần cho phép của mã này.');
    end if;

    -- Tính toán tiền giảm
    if v_promo.discount_type = 'fixed' then 
        v_discount_amount := v_promo.discount_value;
    else 
        v_discount_amount := (p_order_value * v_promo.discount_value) / 100;
        if v_promo.max_discount_value is not null and v_discount_amount > v_promo.max_discount_value then
            v_discount_amount := v_promo.max_discount_value;
        end if;
    end if;
    
    if v_discount_amount > p_order_value then v_discount_amount := p_order_value; end if;

    return json_build_object(
        'valid', true, 
        'message', 'Áp dụng thành công!',
        'discount_amount', v_discount_amount,
        'promotion', row_to_json(v_promo)
    );
end;
$function$
;

grant delete on table "public"."inventory_receipt_items" to "anon";

grant insert on table "public"."inventory_receipt_items" to "anon";

grant references on table "public"."inventory_receipt_items" to "anon";

grant select on table "public"."inventory_receipt_items" to "anon";

grant trigger on table "public"."inventory_receipt_items" to "anon";

grant truncate on table "public"."inventory_receipt_items" to "anon";

grant update on table "public"."inventory_receipt_items" to "anon";

grant delete on table "public"."inventory_receipt_items" to "authenticated";

grant insert on table "public"."inventory_receipt_items" to "authenticated";

grant references on table "public"."inventory_receipt_items" to "authenticated";

grant select on table "public"."inventory_receipt_items" to "authenticated";

grant trigger on table "public"."inventory_receipt_items" to "authenticated";

grant truncate on table "public"."inventory_receipt_items" to "authenticated";

grant update on table "public"."inventory_receipt_items" to "authenticated";

grant delete on table "public"."inventory_receipt_items" to "service_role";

grant insert on table "public"."inventory_receipt_items" to "service_role";

grant references on table "public"."inventory_receipt_items" to "service_role";

grant select on table "public"."inventory_receipt_items" to "service_role";

grant trigger on table "public"."inventory_receipt_items" to "service_role";

grant truncate on table "public"."inventory_receipt_items" to "service_role";

grant update on table "public"."inventory_receipt_items" to "service_role";

grant delete on table "public"."inventory_receipts" to "anon";

grant insert on table "public"."inventory_receipts" to "anon";

grant references on table "public"."inventory_receipts" to "anon";

grant select on table "public"."inventory_receipts" to "anon";

grant trigger on table "public"."inventory_receipts" to "anon";

grant truncate on table "public"."inventory_receipts" to "anon";

grant update on table "public"."inventory_receipts" to "anon";

grant delete on table "public"."inventory_receipts" to "authenticated";

grant insert on table "public"."inventory_receipts" to "authenticated";

grant references on table "public"."inventory_receipts" to "authenticated";

grant select on table "public"."inventory_receipts" to "authenticated";

grant trigger on table "public"."inventory_receipts" to "authenticated";

grant truncate on table "public"."inventory_receipts" to "authenticated";

grant update on table "public"."inventory_receipts" to "authenticated";

grant delete on table "public"."inventory_receipts" to "service_role";

grant insert on table "public"."inventory_receipts" to "service_role";

grant references on table "public"."inventory_receipts" to "service_role";

grant select on table "public"."inventory_receipts" to "service_role";

grant trigger on table "public"."inventory_receipts" to "service_role";

grant truncate on table "public"."inventory_receipts" to "service_role";

grant update on table "public"."inventory_receipts" to "service_role";

grant delete on table "public"."notifications" to "anon";

grant insert on table "public"."notifications" to "anon";

grant references on table "public"."notifications" to "anon";

grant select on table "public"."notifications" to "anon";

grant trigger on table "public"."notifications" to "anon";

grant truncate on table "public"."notifications" to "anon";

grant update on table "public"."notifications" to "anon";

grant delete on table "public"."notifications" to "authenticated";

grant insert on table "public"."notifications" to "authenticated";

grant references on table "public"."notifications" to "authenticated";

grant select on table "public"."notifications" to "authenticated";

grant trigger on table "public"."notifications" to "authenticated";

grant truncate on table "public"."notifications" to "authenticated";

grant update on table "public"."notifications" to "authenticated";

grant delete on table "public"."notifications" to "service_role";

grant insert on table "public"."notifications" to "service_role";

grant references on table "public"."notifications" to "service_role";

grant select on table "public"."notifications" to "service_role";

grant trigger on table "public"."notifications" to "service_role";

grant truncate on table "public"."notifications" to "service_role";

grant update on table "public"."notifications" to "service_role";

grant delete on table "public"."orders" to "anon";

grant insert on table "public"."orders" to "anon";

grant references on table "public"."orders" to "anon";

grant select on table "public"."orders" to "anon";

grant trigger on table "public"."orders" to "anon";

grant truncate on table "public"."orders" to "anon";

grant update on table "public"."orders" to "anon";

grant delete on table "public"."orders" to "authenticated";

grant insert on table "public"."orders" to "authenticated";

grant references on table "public"."orders" to "authenticated";

grant select on table "public"."orders" to "authenticated";

grant trigger on table "public"."orders" to "authenticated";

grant truncate on table "public"."orders" to "authenticated";

grant update on table "public"."orders" to "authenticated";

grant delete on table "public"."orders" to "service_role";

grant insert on table "public"."orders" to "service_role";

grant references on table "public"."orders" to "service_role";

grant select on table "public"."orders" to "service_role";

grant trigger on table "public"."orders" to "service_role";

grant truncate on table "public"."orders" to "service_role";

grant update on table "public"."orders" to "service_role";

grant delete on table "public"."prescription_template_items" to "anon";

grant insert on table "public"."prescription_template_items" to "anon";

grant references on table "public"."prescription_template_items" to "anon";

grant select on table "public"."prescription_template_items" to "anon";

grant trigger on table "public"."prescription_template_items" to "anon";

grant truncate on table "public"."prescription_template_items" to "anon";

grant update on table "public"."prescription_template_items" to "anon";

grant delete on table "public"."prescription_template_items" to "authenticated";

grant insert on table "public"."prescription_template_items" to "authenticated";

grant references on table "public"."prescription_template_items" to "authenticated";

grant select on table "public"."prescription_template_items" to "authenticated";

grant trigger on table "public"."prescription_template_items" to "authenticated";

grant truncate on table "public"."prescription_template_items" to "authenticated";

grant update on table "public"."prescription_template_items" to "authenticated";

grant delete on table "public"."prescription_template_items" to "service_role";

grant insert on table "public"."prescription_template_items" to "service_role";

grant references on table "public"."prescription_template_items" to "service_role";

grant select on table "public"."prescription_template_items" to "service_role";

grant trigger on table "public"."prescription_template_items" to "service_role";

grant truncate on table "public"."prescription_template_items" to "service_role";

grant update on table "public"."prescription_template_items" to "service_role";

grant delete on table "public"."prescription_templates" to "anon";

grant insert on table "public"."prescription_templates" to "anon";

grant references on table "public"."prescription_templates" to "anon";

grant select on table "public"."prescription_templates" to "anon";

grant trigger on table "public"."prescription_templates" to "anon";

grant truncate on table "public"."prescription_templates" to "anon";

grant update on table "public"."prescription_templates" to "anon";

grant delete on table "public"."prescription_templates" to "authenticated";

grant insert on table "public"."prescription_templates" to "authenticated";

grant references on table "public"."prescription_templates" to "authenticated";

grant select on table "public"."prescription_templates" to "authenticated";

grant trigger on table "public"."prescription_templates" to "authenticated";

grant truncate on table "public"."prescription_templates" to "authenticated";

grant update on table "public"."prescription_templates" to "authenticated";

grant delete on table "public"."prescription_templates" to "service_role";

grant insert on table "public"."prescription_templates" to "service_role";

grant references on table "public"."prescription_templates" to "service_role";

grant select on table "public"."prescription_templates" to "service_role";

grant trigger on table "public"."prescription_templates" to "service_role";

grant truncate on table "public"."prescription_templates" to "service_role";

grant update on table "public"."prescription_templates" to "service_role";

grant delete on table "public"."promotion_usages" to "anon";

grant insert on table "public"."promotion_usages" to "anon";

grant references on table "public"."promotion_usages" to "anon";

grant select on table "public"."promotion_usages" to "anon";

grant trigger on table "public"."promotion_usages" to "anon";

grant truncate on table "public"."promotion_usages" to "anon";

grant update on table "public"."promotion_usages" to "anon";

grant delete on table "public"."promotion_usages" to "authenticated";

grant insert on table "public"."promotion_usages" to "authenticated";

grant references on table "public"."promotion_usages" to "authenticated";

grant select on table "public"."promotion_usages" to "authenticated";

grant trigger on table "public"."promotion_usages" to "authenticated";

grant truncate on table "public"."promotion_usages" to "authenticated";

grant update on table "public"."promotion_usages" to "authenticated";

grant delete on table "public"."promotion_usages" to "service_role";

grant insert on table "public"."promotion_usages" to "service_role";

grant references on table "public"."promotion_usages" to "service_role";

grant select on table "public"."promotion_usages" to "service_role";

grant trigger on table "public"."promotion_usages" to "service_role";

grant truncate on table "public"."promotion_usages" to "service_role";

grant update on table "public"."promotion_usages" to "service_role";

grant delete on table "public"."promotions" to "anon";

grant insert on table "public"."promotions" to "anon";

grant references on table "public"."promotions" to "anon";

grant select on table "public"."promotions" to "anon";

grant trigger on table "public"."promotions" to "anon";

grant truncate on table "public"."promotions" to "anon";

grant update on table "public"."promotions" to "anon";

grant delete on table "public"."promotions" to "authenticated";

grant insert on table "public"."promotions" to "authenticated";

grant references on table "public"."promotions" to "authenticated";

grant select on table "public"."promotions" to "authenticated";

grant trigger on table "public"."promotions" to "authenticated";

grant truncate on table "public"."promotions" to "authenticated";

grant update on table "public"."promotions" to "authenticated";

grant delete on table "public"."promotions" to "service_role";

grant insert on table "public"."promotions" to "service_role";

grant references on table "public"."promotions" to "service_role";

grant select on table "public"."promotions" to "service_role";

grant trigger on table "public"."promotions" to "service_role";

grant truncate on table "public"."promotions" to "service_role";

grant update on table "public"."promotions" to "service_role";

grant delete on table "public"."purchase_order_items" to "anon";

grant insert on table "public"."purchase_order_items" to "anon";

grant references on table "public"."purchase_order_items" to "anon";

grant select on table "public"."purchase_order_items" to "anon";

grant trigger on table "public"."purchase_order_items" to "anon";

grant truncate on table "public"."purchase_order_items" to "anon";

grant update on table "public"."purchase_order_items" to "anon";

grant delete on table "public"."purchase_order_items" to "authenticated";

grant insert on table "public"."purchase_order_items" to "authenticated";

grant references on table "public"."purchase_order_items" to "authenticated";

grant select on table "public"."purchase_order_items" to "authenticated";

grant trigger on table "public"."purchase_order_items" to "authenticated";

grant truncate on table "public"."purchase_order_items" to "authenticated";

grant update on table "public"."purchase_order_items" to "authenticated";

grant delete on table "public"."purchase_order_items" to "service_role";

grant insert on table "public"."purchase_order_items" to "service_role";

grant references on table "public"."purchase_order_items" to "service_role";

grant select on table "public"."purchase_order_items" to "service_role";

grant trigger on table "public"."purchase_order_items" to "service_role";

grant truncate on table "public"."purchase_order_items" to "service_role";

grant update on table "public"."purchase_order_items" to "service_role";

grant delete on table "public"."purchase_orders" to "anon";

grant insert on table "public"."purchase_orders" to "anon";

grant references on table "public"."purchase_orders" to "anon";

grant select on table "public"."purchase_orders" to "anon";

grant trigger on table "public"."purchase_orders" to "anon";

grant truncate on table "public"."purchase_orders" to "anon";

grant update on table "public"."purchase_orders" to "anon";

grant delete on table "public"."purchase_orders" to "authenticated";

grant insert on table "public"."purchase_orders" to "authenticated";

grant references on table "public"."purchase_orders" to "authenticated";

grant select on table "public"."purchase_orders" to "authenticated";

grant trigger on table "public"."purchase_orders" to "authenticated";

grant truncate on table "public"."purchase_orders" to "authenticated";

grant update on table "public"."purchase_orders" to "authenticated";

grant delete on table "public"."purchase_orders" to "service_role";

grant insert on table "public"."purchase_orders" to "service_role";

grant references on table "public"."purchase_orders" to "service_role";

grant select on table "public"."purchase_orders" to "service_role";

grant trigger on table "public"."purchase_orders" to "service_role";

grant truncate on table "public"."purchase_orders" to "service_role";

grant update on table "public"."purchase_orders" to "service_role";

grant delete on table "public"."service_package_items" to "anon";

grant insert on table "public"."service_package_items" to "anon";

grant references on table "public"."service_package_items" to "anon";

grant select on table "public"."service_package_items" to "anon";

grant trigger on table "public"."service_package_items" to "anon";

grant truncate on table "public"."service_package_items" to "anon";

grant update on table "public"."service_package_items" to "anon";

grant delete on table "public"."service_package_items" to "authenticated";

grant insert on table "public"."service_package_items" to "authenticated";

grant references on table "public"."service_package_items" to "authenticated";

grant select on table "public"."service_package_items" to "authenticated";

grant trigger on table "public"."service_package_items" to "authenticated";

grant truncate on table "public"."service_package_items" to "authenticated";

grant update on table "public"."service_package_items" to "authenticated";

grant delete on table "public"."service_package_items" to "service_role";

grant insert on table "public"."service_package_items" to "service_role";

grant references on table "public"."service_package_items" to "service_role";

grant select on table "public"."service_package_items" to "service_role";

grant trigger on table "public"."service_package_items" to "service_role";

grant truncate on table "public"."service_package_items" to "service_role";

grant update on table "public"."service_package_items" to "service_role";

grant delete on table "public"."service_packages" to "anon";

grant insert on table "public"."service_packages" to "anon";

grant references on table "public"."service_packages" to "anon";

grant select on table "public"."service_packages" to "anon";

grant trigger on table "public"."service_packages" to "anon";

grant truncate on table "public"."service_packages" to "anon";

grant update on table "public"."service_packages" to "anon";

grant delete on table "public"."service_packages" to "authenticated";

grant insert on table "public"."service_packages" to "authenticated";

grant references on table "public"."service_packages" to "authenticated";

grant select on table "public"."service_packages" to "authenticated";

grant trigger on table "public"."service_packages" to "authenticated";

grant truncate on table "public"."service_packages" to "authenticated";

grant update on table "public"."service_packages" to "authenticated";

grant delete on table "public"."service_packages" to "service_role";

grant insert on table "public"."service_packages" to "service_role";

grant references on table "public"."service_packages" to "service_role";

grant select on table "public"."service_packages" to "service_role";

grant trigger on table "public"."service_packages" to "service_role";

grant truncate on table "public"."service_packages" to "service_role";

grant update on table "public"."service_packages" to "service_role";

grant delete on table "public"."vaccination_template_items" to "anon";

grant insert on table "public"."vaccination_template_items" to "anon";

grant references on table "public"."vaccination_template_items" to "anon";

grant select on table "public"."vaccination_template_items" to "anon";

grant trigger on table "public"."vaccination_template_items" to "anon";

grant truncate on table "public"."vaccination_template_items" to "anon";

grant update on table "public"."vaccination_template_items" to "anon";

grant delete on table "public"."vaccination_template_items" to "authenticated";

grant insert on table "public"."vaccination_template_items" to "authenticated";

grant references on table "public"."vaccination_template_items" to "authenticated";

grant select on table "public"."vaccination_template_items" to "authenticated";

grant trigger on table "public"."vaccination_template_items" to "authenticated";

grant truncate on table "public"."vaccination_template_items" to "authenticated";

grant update on table "public"."vaccination_template_items" to "authenticated";

grant delete on table "public"."vaccination_template_items" to "service_role";

grant insert on table "public"."vaccination_template_items" to "service_role";

grant references on table "public"."vaccination_template_items" to "service_role";

grant select on table "public"."vaccination_template_items" to "service_role";

grant trigger on table "public"."vaccination_template_items" to "service_role";

grant truncate on table "public"."vaccination_template_items" to "service_role";

grant update on table "public"."vaccination_template_items" to "service_role";

grant delete on table "public"."vaccination_templates" to "anon";

grant insert on table "public"."vaccination_templates" to "anon";

grant references on table "public"."vaccination_templates" to "anon";

grant select on table "public"."vaccination_templates" to "anon";

grant trigger on table "public"."vaccination_templates" to "anon";

grant truncate on table "public"."vaccination_templates" to "anon";

grant update on table "public"."vaccination_templates" to "anon";

grant delete on table "public"."vaccination_templates" to "authenticated";

grant insert on table "public"."vaccination_templates" to "authenticated";

grant references on table "public"."vaccination_templates" to "authenticated";

grant select on table "public"."vaccination_templates" to "authenticated";

grant trigger on table "public"."vaccination_templates" to "authenticated";

grant truncate on table "public"."vaccination_templates" to "authenticated";

grant update on table "public"."vaccination_templates" to "authenticated";

grant delete on table "public"."vaccination_templates" to "service_role";

grant insert on table "public"."vaccination_templates" to "service_role";

grant references on table "public"."vaccination_templates" to "service_role";

grant select on table "public"."vaccination_templates" to "service_role";

grant trigger on table "public"."vaccination_templates" to "service_role";

grant truncate on table "public"."vaccination_templates" to "service_role";

grant update on table "public"."vaccination_templates" to "service_role";


  create policy "Enable all for receipt items"
  on "public"."inventory_receipt_items"
  as permissive
  for all
  to authenticated
using (true);



  create policy "Enable all for receipts"
  on "public"."inventory_receipts"
  as permissive
  for all
  to authenticated
using (true);



  create policy "User view own noti"
  on "public"."notifications"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "Staff can view all orders"
  on "public"."orders"
  as permissive
  for select
  to public
using (((auth.uid() = creator_id) OR (EXISTS ( SELECT 1
   FROM public.user_roles
  WHERE (user_roles.user_id = auth.uid())))));



  create policy "Enable delete items"
  on "public"."prescription_template_items"
  as permissive
  for delete
  to public
using ((auth.role() = 'authenticated'::text));



  create policy "Enable insert items"
  on "public"."prescription_template_items"
  as permissive
  for insert
  to public
with check ((auth.role() = 'authenticated'::text));



  create policy "Enable read access items"
  on "public"."prescription_template_items"
  as permissive
  for select
  to public
using (true);



  create policy "Enable update items"
  on "public"."prescription_template_items"
  as permissive
  for update
  to public
using ((auth.role() = 'authenticated'::text));



  create policy "Enable delete for authenticated users only"
  on "public"."prescription_templates"
  as permissive
  for delete
  to public
using ((auth.role() = 'authenticated'::text));



  create policy "Enable insert for authenticated users only"
  on "public"."prescription_templates"
  as permissive
  for insert
  to public
with check ((auth.role() = 'authenticated'::text));



  create policy "Enable read access for all users"
  on "public"."prescription_templates"
  as permissive
  for select
  to public
using (true);



  create policy "Enable update for authenticated users only"
  on "public"."prescription_templates"
  as permissive
  for update
  to public
using ((auth.role() = 'authenticated'::text));



  create policy "Enable all for items"
  on "public"."purchase_order_items"
  as permissive
  for all
  to authenticated
using (true);



  create policy "Enable all for authenticated"
  on "public"."purchase_orders"
  as permissive
  for all
  to authenticated
using (true);



  create policy "Allow authenticated full access on service_package_items"
  on "public"."service_package_items"
  as permissive
  for all
  to authenticated
using (true)
with check (true);



  create policy "Allow authenticated full access on service_packages"
  on "public"."service_packages"
  as permissive
  for all
  to authenticated
using (true)
with check (true);



  create policy "Authenticated users can delete items"
  on "public"."vaccination_template_items"
  as permissive
  for delete
  to authenticated
using (true);



  create policy "Authenticated users can insert items"
  on "public"."vaccination_template_items"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Authenticated users can select items"
  on "public"."vaccination_template_items"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Authenticated users can update items"
  on "public"."vaccination_template_items"
  as permissive
  for update
  to authenticated
using (true);



  create policy "Authenticated users can delete templates"
  on "public"."vaccination_templates"
  as permissive
  for delete
  to authenticated
using (true);



  create policy "Authenticated users can insert templates"
  on "public"."vaccination_templates"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Authenticated users can select templates"
  on "public"."vaccination_templates"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Authenticated users can update templates"
  on "public"."vaccination_templates"
  as permissive
  for update
  to authenticated
using (true);


CREATE TRIGGER on_updated_at BEFORE UPDATE ON public.service_packages FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();


